### ISSUE TITLE
Format numbers

### ISSUE THREAD

**Issue by Maraumax** [arnapou/gw2tools#3]
Example in Wallet, why not format numbers ? (3284235 become 3 284 235 or 3.284.235)

**Comment by arnapou** [comment]
Because I didn't took the time to manage localized integers. It was fastest for me to render the raw number.

Gw2tools is a personal project I share, I don't and won't have time to maintain lots of thing on it. That's the main reason why I share the code : if people want to enhance things and make PR, it would be nice. But in facts : nobody made any PR since the begining. 

The reasonning is there : if nobody is interested, why should I spend more time than what I do which is enough for me ?

I publicly shared informations on reddit years ago but a lot of people where just blind downvoters who said "why doing another gw2efficiency website which is less good". I tried to argue that gw2tools has things better than gw2efficiency but nobody cares (stuff oriented, linked with gw2skills templates, better privacy, open source, no feature which is not in the official API, ...). I just let them do whatever they want, and I continue to add features for me when I want : if people use or not gw2tools, I don't care anymore. If they want features and things in gw2tools : they have to made PR and participate.

My answer was longer than I wanted but I guess It is now clear for you why I won't "fix" this issue.

**Comment by Maraumax** [comment]
Salut,

Je me permet de répondre en Français of course ! Je me suis permis de créer deux tickets mais pas pour que tu t'empresse de les mettre en place parce que franchement ce n'est pas dérangeant mais plus pour participer un peu au projet et pourquoi pas apporter / proposer moi même ces améliorations !

Ton projet est super cool, je suis pas (plus) un gros geek de GW2 mais j'aime bien aller consulter un peu les stats dessus et si j'ai un peu de temps j'hésiterais pas à regarder un peu ton code et pourquoi pas proposer des PR.

Après pour reddit je suis que pas étonné, j'ai aussi eu plusieurs projets et les critiques sont loin d'être toujours constructives :)

En tout cas n'hésite pas à ré-ouvrir l'issue avec un tag #todo :)
